version: '2.3'
services:
  netdisco-postgresql:
    image: farktronix/netdisco-arm:latest-postgresql
    volumes:
      - "./netdisco/pgdata:/var/lib/postgresql/data"
#    build:
#      context: netdisco-postgresql
#  netdisco-base:
#    image: netdisco/netdisco:latest-base
#    build:
#      context: netdisco-base
#    scale: 0
  netdisco-backend:
    image: farktronix/netdisco-arm:latest-backend
    volumes:
      - "./netdisco/nd-site-local:/home/netdisco/nd-site-local"
      - "./netdisco/config:/home/netdisco/environments"
      - "./netdisco/logs:/home/netdisco/logs"
    environment:
      NETDISCO_DOMAIN:  discover
      NETDISCO_DB_HOST: netdisco-postgresql
    depends_on:
      - netdisco-postgresql
#    build:
#      context: netdisco-backend
  netdisco-web:
    image: farktronix/netdisco-arm:latest-web
    volumes:
      - "./netdisco/nd-site-local:/home/netdisco/nd-site-local"
      - "./netdisco/config:/home/netdisco/environments"
      - "./netdisco/logs:/home/netdisco/logs"
    environment:
      NETDISCO_DOMAIN:  discover
      NETDISCO_DB_HOST: netdisco-postgresql
    ports:
      - "5000:5000"
    depends_on:
      - netdisco-postgresql
#    build:
#      context: netdisco-web
#networks:
#  default:
#    enable_ipv6: true
